# Generated by Django 4.2.10 on 2025-03-11 22:55

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import news.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('title', models.CharField(max_length=100, verbose_name='Título/Especialidade')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descrição')),
                ('photo', models.ImageField(upload_to=news.models.get_partner_image_path, verbose_name='Foto')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletters'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news', verbose_name='Notícia'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news.comment', verbose_name='Comentário Pai'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(upload_to=news.models.get_file_path, verbose_name='Imagem Destacada'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Em Destaque'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_slider',
            field=models.BooleanField(default=False, verbose_name='No Slider'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_trending',
            field=models.BooleanField(default=False, verbose_name='Em Tendência'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=200, unique_for_date='publish_date', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, max_length=500, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subscribed_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição'),
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('preferred_days', models.CharField(max_length=200, verbose_name='Dias Preferidos')),
                ('preferred_times', models.CharField(max_length=200, verbose_name='Horários Preferidos')),
                ('payment_method', models.CharField(choices=[('credit', 'Cartão de Crédito'), ('debit', 'Cartão de Débito'), ('pix', 'PIX'), ('bank_transfer', 'Transferência Bancária'), ('cash', 'Dinheiro')], max_length=20, verbose_name='Forma de Pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Status')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='news.partner', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Solicitação de Consulta',
                'verbose_name_plural': 'Solicitações de Consulta',
                'ordering': ['-created_date'],
            },
        ),
    ]
