# Generated by Django 5.2.1 on 2025-05-13 00:29

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_partner_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(help_text='Formatos aceitos: JPG, JPEG, PNG. Tamanho máximo: 5MB', upload_to=news.models.get_file_path, verbose_name='Imagem Destacada'),
        ),
    ]
