# Generated by Django 5.2.1 on 2025-05-13 00:33

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(help_text='Formatos aceitos: JPG, JPEG, PNG. Tamanho máximo: 5MB', max_length=255, upload_to=news.models.get_file_path, verbose_name='Imagem Destacada'),
        ),
    ]
