# Generated by Django 5.2.1 on 2025-05-13 00:36

import time
import os

from django.db import migrations, models

def news_image_path_legacy(instance, filename):
    """Função de migração para compatibilidade"""
    ext = filename.split('.')[-1].lower()
    if ext not in ['jpg', 'jpeg', 'png']:
        ext = 'jpg'
    simple_name = f"news_{int(time.time())}.{ext}"
    return simple_name

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(max_length=255, upload_to=news_image_path_legacy, verbose_name='Imagem Destacada'),
        ),
    ]
