# Generated by Django 5.2.1 on 2025-05-13 00:59

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(max_length=255, upload_to=news.models.news_image_upload_path, verbose_name='Imagem Destacada'),
        ),
    ]
