# Generated by Django 5.2.1 on 2025-05-13 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('url', models.URLField(max_length=255, verbose_name='URL do Feed')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='rss_logos/', verbose_name='Logo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('max_items', models.PositiveIntegerField(default=5, verbose_name='Máximo de Itens')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Feed RSS',
                'verbose_name_plural': 'Feeds RSS',
                'ordering': ['order', 'name'],
            },
        ),
    ]
