# Generated by Django 5.2.1 on 2025-05-15 14:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rssfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=10000, verbose_name='Conteúdo'),
        ),
    ]
