# Generated by Django 5.2.1 on 2025-05-15 15:06

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(help_text='Obrigatório: Adicione uma imagem para a notícia', max_length=255, upload_to=news.models.news_image_upload_path, verbose_name='Imagem Destacada'),
        ),
    ]
